name: Unit testing on ubuntu

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install lacmus
      run: |
        python -m pip install --upgrade pip
        pip install tensorflow==1.14
        pip install keras==2.3.1
        pip install opencv-python
        pip install --upgrade setuptools
        pip install -U numpy==1.16
        pip install .
        python setup.py build_ext --inplace
        pip install pytest
    - name: Run tests
      run: pytest tests